[package]
name = "img-convert-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
image= {version =  "0.25.6" }
webp="0.3.0"
clap = { version = "4.5.37", features = ["derive"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.31"